github-action.json
name: 'greetings'
description: 'Hello World'
inputs: 
  who-to-greet: 'Enter the name of the person whom you want to greet'
  default: 'Jyotsna Wadhwani'
  required: true
outputs:
  time: 
    description: 'When I have greeted'
runs:
  using: 'node12'
  main: 'index.js'
